### ISSUE TITLE
Attachment selection not functional

### ISSUE THREAD

**Issue by marxistvegan** [QtGram/SailorGram-BETA#1]
Installed it today for a test run and found that when pressing on the attachments paperclip it does not advance to another screen. Not sure if this is a known bug.

**Comment by lewadedun** [comment]
+

**Comment by Dax89** [comment]
Message upload will be available in the first beta, I have an "internal" alpha which is light years away compared to the one available there.

I will upload it now

**Comment by Dax89** [comment]
Alpha 5: https://github.com/QtGram/SailorGram-BETA/blob/master/alpha/harbour-sailorgram-0.89-5.armv7hl.rpm?raw=true

**Comment by lewadedun** [comment]
Begin testing )

**Comment by Dax89** [comment]
Changelog is there too :)

**Comment by z3bratabs** [comment]
I just installed 0.89.5, and this issue is still present. Is there another way to send attachement, eg. using the "Share" item from the pulley menu?

**Comment by Dax89** [comment]
It's not an issue, 0.89-5 is in development and that feature is not restored yet.

If you want a usable client, get 0.80 from open repos
