### ISSUE TITLE
"Message..." field desappears when scrolling

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#10]
When you are on a chat (personal, group or anything else) and scroll, the "Message..." field disappears on the botton side of the screen, being impossible to write if you aren't at the end of the conversation (see attachment).
![captura_20161114_011](https://cloud.githubusercontent.com/assets/1192395/20272567/99a69162-aa8e-11e6-87d2-ffaded228299.png)
![captura_20161114_010](https://cloud.githubusercontent.com/assets/1192395/20272576/9d037adc-aa8e-11e6-8099-e387d00ce099.png)

**Comment by Dax89** [comment]
That's a wanted behavior because the field is part of the message list
