### ISSUE TITLE
Sailorgram disconnects when changing between networks 

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#11]
When switching between networks (pe, WiFi and 3G) Sailorgram disconnets and it can't reconnect.
![captura_20161115_001](https://cloud.githubusercontent.com/assets/1192395/20300290/c69b4182-ab1e-11e6-8bfc-51e2f3843b5d.png)

**Comment by lewadedun** [comment]
confirm

**Comment by marxistvegan** [comment]
It is a soft disconnect now in the Beta 2 where it appears online but in fact one is off line. Only able to reconnect by close the app and restarting it.

**Comment by Dax89** [comment]
I'm working on that!

**Comment by Dax89** [comment]
Should be fixed in beta 3

**Comment by ferlanero** [comment]
Working as expected! Good work! Close this issue ;) #
