### ISSUE TITLE
Random closures in Sailorgram (files uploading)

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#15]
When uploading a file (p.e a picture), when it ends, it forces the closing of Sailorgram

**Comment by Dax89** [comment]
Should be fixed in the upcoming beta 3

**Comment by Dax89** [comment]
Beta 3 is now public, let me know if this issue is present!

**Comment by TomiOhl** [comment]
No FC on sending images, but how to send files?

**Comment by Dax89** [comment]
The docked bar provides: Pictures, Files, Location (in this order)

**Comment by TomiOhl** [comment]
Strange, I have only two options: http://i.imgur.com/cl59QJX.jpg
(that message which is displayed incorrectly is the sailorgram beta3 file)

**Comment by Dax89** [comment]
Mmmmh, I think that you SailfishOS version doesn't provide the selected icon.

Which version of SailfishOS are you running?

**Comment by TomiOhl** [comment]
2.0.1.11
This can be the reason also for some characters not displaying correctly? I mean, I have a crossed box before chats' names too.

**Comment by Dax89** [comment]
Yes, because I'm using unicode characters instead of small pictures, so I can color/resize it according to the chat's title.

**Comment by TomiOhl** [comment]
I see. When were these characters added? Are they there in 2.0.2.51?

And screenshot from android: http://i.imgur.com/UW9iqJA.jpg

**Comment by Dax89** [comment]
Ah, ok so it's an "internal" message, It shouldn't be displayed, thanks :)
It's the same release where SailfishOS support emojis, yes 2.0.2.x .

Another workaround is to install a custom font from open repos.

**Comment by TomiOhl** [comment]
Ok, thanks. So if I installed sailfish on my primary device, I would have emoji support built-in (2.0.4 is also in development for that one).

**Comment by ferlanero** [comment]
Confirmed: not issue sending files ;)
