### ISSUE TITLE
Random closures in Sailorgram (receiving new message)

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#16]
When you are in Sailorgram receiving a new message, it forces Sailorgram to close

**Comment by Dax89** [comment]
Should be fixed in the upcoming beta 3

**Comment by TomiOhl** [comment]
Actually, I have closures mainly after I send something in a supergroup. Normal chat is fine. Hope this one will be fixed too.

**Comment by Dax89** [comment]
That's a different issue: the library stops because has detected an undefined behavior, I need to send a message in a supergroup in order to fix it.

**Comment by TomiOhl** [comment]
Oh, I see.

**Comment by Dax89** [comment]
Should be fixed in beta 3

**Comment by ferlanero** [comment]
Solved. No more closes when receiving new messages from group, supergroup or personal chats.

**Comment by Dax89** [comment]
Great!
