### ISSUE TITLE
[beta-3] client crash when coversation get deleted 

### ISSUE THREAD

**Issue by Nokius** [QtGram/SailorGram-BETA#18]
When I deleted a conversation the client crashed

**Comment by Dax89** [comment]
I already have a log of that, fix in beta 4

**Comment by ferlanero** [comment]
I can confirm this bug

**Comment by Dax89** [comment]
Fixed in https://github.com/QtGram/LibQTelegram/commit/fbdfa3c128ed9bb99a4f414027b45f1ba7b29411
