### ISSUE TITLE
Text input box shows in transparent

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#20]
In beta 3 the text input box in the downside of Sailorgram shows in transparent mode, which difficults entering text when scrolling. Better in a solid color.
![captura_20161127_001](https://cloud.githubusercontent.com/assets/1192395/20647925/74ea7842-b499-11e6-9793-fb7f4c64da13.png)

**Comment by TomiOhl** [comment]
I agree

**Comment by Dax89** [comment]
Fixed in https://github.com/QtGram/harbour-sailorgram/commit/7a887b44faa527d021ff760c4baf29bc376e1645
