### ISSUE TITLE
No posibility to download files

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#22]
In Sailorgram Beta 3 there is no chance of downloading files neither in groups, supergroups, channels nor personal chats
![captura_20161127_002](https://cloud.githubusercontent.com/assets/1192395/20648024/fe43a332-b49b-11e6-8c23-18910ca68e69.png)

**Comment by Dax89** [comment]
Yes, it's not handled, thanks for reporting it :)

**Comment by Dax89** [comment]
Fixed in https://github.com/QtGram/harbour-sailorgram/commit/835863202c053138335a36f99300ef662a08d8d0
