### ISSUE TITLE
[enhancement] Show an alert when Sailorgram opens an external program

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#26]
It'd be great if Sailorgram alerted when opening the web browser after clicking a link
![captura_20161128_002](https://cloud.githubusercontent.com/assets/1192395/20653166/10bfd414-b509-11e6-8cfa-818672cb79c7.png)

**Comment by Dax89** [comment]
Notification is now displayed for:
* Images
* Location
* Files
* URLs
* When a picture is saved manually in download folder

Fixed in: https://github.com/QtGram/harbour-sailorgram/commit/8f629a9a6936dfb2bb65805b64df163fd87e14e7
