### ISSUE TITLE
Messages count doesn't show real state after entering and read news in channels, groups, personal chats

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#5]
Messages count doesn't show real state after entering and read news in channels, groups, personal chats.
You have to enter at least twice in order to messages count shows real state.
![captura_20161114_005](https://cloud.githubusercontent.com/assets/1192395/20266152/1c49dbb6-aa75-11e6-9acd-cdbf338e824d.png)

**Comment by Dax89** [comment]
Fixed today :D
