### ISSUE TITLE
Clicking notification doesn't open Sailorgram

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#6]
When you click on new messages notification, nothing happens. Just notification disappears without opening Sailorgram client.
![captura_20161114_006](https://cloud.githubusercontent.com/assets/1192395/20269791/fd82ba1c-aa84-11e6-8e45-58e8985af902.png)

**Comment by Dax89** [comment]
Strange, It should work, usually it takes a while.
It's even possible that there is a regression from the last two alphas, I will take a look at that

**Comment by ferlanero** [comment]
Works correctly in beta 3. When Sailorgram is minimized and click on notification, now it opens the client. Solved.
