### ISSUE TITLE
[UPDATE REQUEST] Opening link notification

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#7]
It would be good if Sailorgram notifies when you click on a link which opens an external browser (see attachment)
![captura_20161114_007](https://cloud.githubusercontent.com/assets/1192395/20270123/1fe49d18-aa86-11e6-9b61-b8cb617001a5.png)

**Comment by Dax89** [comment]
Implemented in https://github.com/QtGram/harbour-sailorgram/commit/9b77852a75fda3ce9f343f545eabe5b382d7f061
