### ISSUE TITLE
Clicking on a contact from the contact list, does nothing

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#8]
When you go to "Contacts" and click over any of then there, nothing happens, which makes unable to start a normal or private conversation.
![captura_20161114_008](https://cloud.githubusercontent.com/assets/1192395/20270302/d9a18bbc-aa86-11e6-89f4-d865096ab3f9.png)

**Comment by Dax89** [comment]
mmmh, it can be enabled now, thanks for remind this issue! :)

**Comment by ferlanero** [comment]
Just saying what I'm watching ;)

**Comment by Dax89** [comment]
Fixed in e17712b5f378382ee03677b655907b6522638c33
