### ISSUE TITLE
Sailorgram doesn't show correctly downloable files.

### ISSUE THREAD

**Issue by ferlanero** [QtGram/SailorGram-BETA#9]
When clicking on a file which could be downloaded from Telegram, Sailorgram doesn't show it properly and it can't be downloaded in fact.
![captura_20161114_009](https://cloud.githubusercontent.com/assets/1192395/20271055/b8fc71ee-aa89-11e6-8f86-ced71ccd2a35.png)

**Comment by Dax89** [comment]
Fixed in https://github.com/QtGram/harbour-sailorgram/commit/e58240a51f3f4cb5f547efc9b758604a048b9e6c
